version: "2.2"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'tarea2'
      MYSQLUSER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./my-db:/var/lib/mysql
      - ./archivos:/archivos

  backend:
    build: ./backend
    container_name: tarea2
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - db
